postgres:
  image: postgres:17.4
  username: postgres
  password: amir
  storage: 1Gi

fruitService:
  image: amirabidii/fruit_back_amir:v2.0.200
  port: 8081
  nodePort: 30001

legumeService:
  image: amirabidii/legume_back_amir:v2.0.50
  port: 8080
  nodePort: 30002

frontend:
  image: amirabidii/myfront_service:1.0.95
  port: 4200
  nodePort: 30000

# ================================
# PROMETHEUS CONFIGURATION
# ================================
prometheus:
  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: "fruit-service"
          metrics_path: "/actuator/prometheus"
          static_configs:
            - targets: ["fruit-service-back:8081"]

        - job_name: "legume-service"
          metrics_path: "/actuator/prometheus"
          static_configs:
            - targets: ["legume-service-back:8080"]

        - job_name: "prometheus"
          static_configs:
            - targets: ["localhost:9090"]



# ================================
# GRAFANA CONFIGURATION
# ================================
grafana:
  adminPassword: "admin123"
  service:
    type: NodePort
    nodePort: 32000
