apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db
data:
  init-multiple-db.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
        CREATE DATABASE fruitdb;
        CREATE DATABASE legumedb;
    EOSQL
    