apiVersion: apps/v1
kind: Deployment
metadata:
  name: fruit-service-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fruit-service-back
  template:
    metadata:
      labels:
        app: fruit-service-back
    spec:
      containers:
        - name: fruit-service-back
          image: {{ .Values.fruitService.image }}
          ports:
            - containerPort: {{ .Values.fruitService.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/fruitdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.postgres.username | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.postgres.password | quote }}
